#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleMThreads
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="att")]
	public partial class AttDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTFTAttLog(TFTAttLog instance);
    partial void UpdateTFTAttLog(TFTAttLog instance);
    partial void DeleteTFTAttLog(TFTAttLog instance);
    #endregion
		
		public AttDataClassesDataContext() : 
				base(global::ConsoleMThreads.Properties.Settings.Default.attConnectionString4, mappingSource)
		{
			OnCreated();
		}
		
		public AttDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AttDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AttDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AttDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TFTAttLog> TFTAttLogs
		{
			get
			{
				return this.GetTable<TFTAttLog>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TFTAttLogs")]
	public partial class TFTAttLog : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Ip;
		
		private string _EnrollNumber;
		
		private string _VerifyMode;
		
		private string _InOutMode;
		
		private string _Time;
		
		private string _WorkCode;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnIpChanging(string value);
    partial void OnIpChanged();
    partial void OnEnrollNumberChanging(string value);
    partial void OnEnrollNumberChanged();
    partial void OnVerifyModeChanging(string value);
    partial void OnVerifyModeChanged();
    partial void OnInOutModeChanging(string value);
    partial void OnInOutModeChanged();
    partial void OnTimeChanging(string value);
    partial void OnTimeChanged();
    partial void OnWorkCodeChanging(string value);
    partial void OnWorkCodeChanged();
    #endregion
		
		public TFTAttLog()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ip", DbType="NChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Ip
		{
			get
			{
				return this._Ip;
			}
			set
			{
				if ((this._Ip != value))
				{
					this.OnIpChanging(value);
					this.SendPropertyChanging();
					this._Ip = value;
					this.SendPropertyChanged("Ip");
					this.OnIpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnrollNumber", DbType="NChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string EnrollNumber
		{
			get
			{
				return this._EnrollNumber;
			}
			set
			{
				if ((this._EnrollNumber != value))
				{
					this.OnEnrollNumberChanging(value);
					this.SendPropertyChanging();
					this._EnrollNumber = value;
					this.SendPropertyChanged("EnrollNumber");
					this.OnEnrollNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VerifyMode", DbType="NChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string VerifyMode
		{
			get
			{
				return this._VerifyMode;
			}
			set
			{
				if ((this._VerifyMode != value))
				{
					this.OnVerifyModeChanging(value);
					this.SendPropertyChanging();
					this._VerifyMode = value;
					this.SendPropertyChanged("VerifyMode");
					this.OnVerifyModeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InOutMode", DbType="NChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string InOutMode
		{
			get
			{
				return this._InOutMode;
			}
			set
			{
				if ((this._InOutMode != value))
				{
					this.OnInOutModeChanging(value);
					this.SendPropertyChanging();
					this._InOutMode = value;
					this.SendPropertyChanged("InOutMode");
					this.OnInOutModeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Time", DbType="NChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Time
		{
			get
			{
				return this._Time;
			}
			set
			{
				if ((this._Time != value))
				{
					this.OnTimeChanging(value);
					this.SendPropertyChanging();
					this._Time = value;
					this.SendPropertyChanged("Time");
					this.OnTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WorkCode", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string WorkCode
		{
			get
			{
				return this._WorkCode;
			}
			set
			{
				if ((this._WorkCode != value))
				{
					this.OnWorkCodeChanging(value);
					this.SendPropertyChanging();
					this._WorkCode = value;
					this.SendPropertyChanged("WorkCode");
					this.OnWorkCodeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
